### PR TITLE
Rubyversion

### PR DESCRIPTION
**Pull request by seanfcarroll**
Upgrade to Ruby 2.5.0 and use rails 5 binstubs.
Fix "applications" page error

### CODE REVIEW

**Comment by seanfcarroll** [comment]
Actually @nbulaj I found some other issues with older versions of code still there (eg: in the views), and in the end built my own sample apps on Rails 5.1 from scratch. I can polish them a bit and then hand them over you. Let me know.

https://github.com/seanfcarroll/doorkeeper-provider-devise-rails-5.1

https://github.com/seanfcarroll/doorkeeper-client-rails-5.1

**Comment by nbulaj** [comment]
hi @seanfcarroll . What are the problems with the current sample? I think you can merge all the nifty things from your app to this one.

**Comment by nbulaj** [comment]
Hi @seanfcarroll . Any news here?

**Comment by nbulaj** [comment]
Ping @seanfcarroll

**Comment by stulentsev** [comment]
@nbulaj here's one of the problems:

``` ruby
ActionView::Template::Error (undefined method `oauth_doorkeeper_applications_path' for #<#<Class:0x00007f4496f2d6e0>:0x00007f4496d7fa50>
Did you mean?  oauth_authorized_applications_path):
    1: <%= form_for( [:oauth, application] ) do |f| %>
    2:   <fieldset>
    3:     <% if @application.errors.any? %>
    4:       <div class="alert alert-error">
  
app/views/doorkeeper/applications/_form.html.erb:1:in `_app_views_doorkeeper_applications__form_html_erb__3258833442825523983_69966282579560'
app/views/doorkeeper/applications/new.html.erb:6:in `_app_views_doorkeeper_applications_new_html_erb___1788451124711228921_69966283501500'
```

**Comment by felipeelias** [comment]
@stulentsev I run into the same issue today, I'm investigating it at the moment

**Comment by felipeelias** [comment]
@stulentsev I believe I fixed the view issues on #23

**Comment by felipeelias** [comment]
@seanfcarroll I believe I fixed all significant issues in the master branch, please revert your changes to the views since they're not necessary. I hope this will help you with your first contribution to this repo!

**Comment by felipeelias** [comment]
Sorry to close your PR, but I already spend some additional time meantime upgrading it to newer Ruby.

The application now is live again on:
- https://doorkeeper-provider.herokuapp.com/

And client app as well, on:
- https://doorkeeper-sinatra.herokuapp.com/

There will be some additional work to upgrade Doorkeeper to newer version, let me know if this is something you'd like to work on.

**Pull request closed without merging**
